source 'https://rubygems.org'


gem 'rails', '4.1.6'

gem 'rails-api'

gem 'rack-cors', :require => 'rack/cors'

gem 'pg'

gem 'bcrypt', '~> 3.1.7'

group :test, :development do
	gem 'rspec-rails', '~> 3.0'
	gem 'spring'
	gem 'capybara'
	gem 'factory_girl_rails'
	gem 'faker'
	gem 'shoulda-matchers', require: false
	gem 'railroady'
end

gem 'carrierwave'
gem 'cloudinary'


gem 'safe_attributes'

gem 'httparty'


# To use ActiveModel has_secure_password
# 

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
